name: Continuous-Integration

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      browserName:
        description: "Browser Type"
        required: false
        type: "string"
        default: "chrome"

jobs:
  start-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "corretto"
      - name: Set target browserName in environment variables
        run: echo "BROWSER_NAME=${{ inputs.browserName || 'CHROME' }}" >> $GITHUB_ENV
      - name: Build using maven
        run: mvn clean
      - name: Run tests
        run: mvn -DbrowserName=${{ BROWSER_NAME }} verify