name: Continuous-Integration

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      browserName:
        description: "Browser Type"
        required: false
        type: "string"
        default: "chrome"

jobs:
  start-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "corretto"
      - name: Set target browserName in environment variables
        run: echo "BROWSER_NAME=${{ inputs.browserName || 'CHROME' }}" >> $GITHUB_ENV
      - name: Build using maven
        run: mvn clean install -DskipTests
      - name: Run tests
        run: mvn -DbrowserName=$BROWSER_NAME verify
  build-report:
    needs: start-test
    runs-on: ubuntu-latest
    steps:
      - name: Get Allure test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-page-report
          path: gh-page-report
      - name: Build Allure test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-page-report
          allure_report: allure-report
          allure_history: allure-history
          allure_results: ${{ vars.ALLURE_RESULTS_PATH }}
  publish-report:
    needs: [start-test, build-report]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy report to GitHub Pages
        if: always()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-page-report
          build_dir: allure-history
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}